<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>BlackHole.Demo</RootNamespace>
    <AssemblyName>BlackHole.Demo</AssemblyName>
    <IsPackable>false</IsPackable>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../BlackHole/BlackHole.csproj" />
  </ItemGroup>

</Project>
