<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>BlackHole.InteropServer</RootNamespace>
    <AssemblyName>BlackHole.InteropServer</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/BlackHole/BlackHole.csproj" />
  </ItemGroup>

</Project>
